on: push 
if: github.ref == 'refs/heads/main'

jobs:

  build_and_deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: checkout  
      uses: actions/checkout@v4

    - name: build and deploy
      uses: shalzz/zola-deploy-action@v0.17.2
      env:
        PAGES_BRANCH: gh-pages
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
